{{- if .Values.app.db.use }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-auth
data:
  user: {{ .Values.app.db.user | b64enc }}
  pass: {{ .Values.app.db.pass | toString | b64enc }}
{{- end }}