apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.app.ports.service }}
    targetPort: {{ .Values.app.ports.container }}
  selector:
    app: {{ .Release.Name }}
